default:
    @just --list

build-app:
    uv sync
    uv run python manage.py collectstatic --noinput

build-image:
    docker build -t frontend .

setup-app:
    uv run python manage.py createsuperuser
    uv run python manage.py loaddata posts.json

clear-sessions:
    uv run python manage.py clearsessions

media-dir:
    mkdir -p data data/media

migrate-app:
    uv run python manage.py migrate --noinput

start-app: media-dir migrate-app
    uv run ./app.sh
